/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.studiodanca.lpoo_sistemastudiodanca.view;

import br.edu.ifsul.cc.lpoo.studiodanca.lpoo_sistemastudiodanca.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.studiodanca.lpoo_sistemastudiodanca.model.Modalidade;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author kurum
 */
public class TelaModalidades extends javax.swing.JFrame {

    /**
     * Creates new form TelaModalidades
     */

    private PersistenciaJPA jpa;
    private DefaultListModel<String> mod;

    public TelaModalidades() {
        initComponents();
        jpa = new PersistenciaJPA();
        mod = new DefaultListModel<>();
        lstModalidades.setModel(mod);
        listarModalidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstModalidades = new javax.swing.JList<>();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(215, 142, 188));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lstModalidades.setBackground(new java.awt.Color(197, 230, 188));
        lstModalidades.setBorder(new javax.swing.border.MatteBorder(null));
        lstModalidades.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lstModalidades.setForeground(new java.awt.Color(215, 142, 188));
        lstModalidades.setToolTipText("");
        lstModalidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(lstModalidades);

        btnEditar.setBackground(new java.awt.Color(197, 230, 188));
        btnEditar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(215, 142, 188));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(197, 230, 188));
        btnNovo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(215, 142, 188));
        btnNovo.setText("Adicionar Modalidade");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnRemover.setBackground(new java.awt.Color(197, 230, 188));
        btnRemover.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(215, 142, 188));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarModalidades() {
        mod.clear();
        List<Modalidade> modalidades = jpa.getModalidades();
        for (Modalidade m : modalidades) {
            mod.addElement(m.getDescricao());
        }
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String modalidadeSelecionada = lstModalidades.getSelectedValue();

        if (modalidadeSelecionada != null) {
            String novaDescricao = JOptionPane.showInputDialog(this, "Digite a nova descrição da modalidade:", modalidadeSelecionada);

            if (novaDescricao != null && !novaDescricao.trim().isEmpty()) {
                try {
                    if (!jpa.conexaoAberta()) {
                        jpa = new PersistenciaJPA();
                    }

                    List<Modalidade> modalidades = jpa.getModalidades();
                    for (Modalidade m : modalidades) {
                        if (m.getDescricao().equals(modalidadeSelecionada)) {
                            m.setDescricao(novaDescricao);
                            jpa.persist(m);
                            break;
                        }
                    }

                    JOptionPane.showMessageDialog(this, "Modalidade editada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao editar a modalidade: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
                listarModalidades();
            } else {
                JOptionPane.showMessageDialog(this, "A nova descrição da modalidade não pode ser vazia.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma modalidade para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        TelaCadastroModalidade telaCadastro = new TelaCadastroModalidade(this, true, jpa);
        telaCadastro.setVisible(true);

        listarModalidades();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:

        String modalidadeSelecionada = lstModalidades.getSelectedValue();

        if (modalidadeSelecionada != null) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja remover a modalidade?", "Confirmação", JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    if (!jpa.conexaoAberta()) {
                        jpa = new PersistenciaJPA();
                    }

                    List<Modalidade> modalidades = jpa.getModalidades();
                    for (Modalidade m : modalidades) {
                        if (m.getDescricao().equals(modalidadeSelecionada)) {
                            jpa.remover(m);
                            break;
                        }
                    }

                    JOptionPane.showMessageDialog(this, "Modalidade removida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover a modalidade: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
                listarModalidades();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma modalidade para remover.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModalidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstModalidades;
    // End of variables declaration//GEN-END:variables
}
